language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

  coverity_scan:
    project:
      name: "vicrucann/QtOSG-hello"
      description: "<Your project description here>"
    notification_email: vicrucann@gmail.com
    build_command:   "make VERBOSE=1"
    branch_pattern: coverity_scan

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #    #   via the "travis encrypt" command using the project repo's public key #       
    - secure: "Nos21UVspgAwvH1hNa9KFxmkNj+y3vQ47DrVGSh5DlO2oYFpFEERQBkLkf685/OyfKtSsHl95CWcRdpH9ZiI6LOhL6XGgqh9TOHI1WA3trGwJWZ6jFBZIX/DihBB2YcTHTxpOs8wm1lAA14d+vaMjrjeCt0YjGjI21mdKP8RtcalguhZeBKV0MdFDYdKBexZtIiVTSLV2/UiJ15+x7O2jtk0kIJV91f/rS9Usc0QC9w1a6pamtw63rhqXARnU5peilYGgXucuZctnK26eMiPfXCMP7XE8ECubpa7rhLGEl5qBWJxKPzyE4HiHKtL3Bj7F8IFfVBnG2aF/eWhYWCHnqq7aoFvdGXFx/f0Dd9MHuaLAV32zMV/aEXtTEfd7XoF/J6riMSyNRHzSxFXy70kXO8FgLjuPKTB7eVBdxolVmFPdhVVtyiRuJPKIt43Zkhbbran6JJ7AQx99Y6z/qnQhTqXaDy2NELXbkNLEb7pK9VEF974DIGzEiKl1XFCpZtDOf48Sbe1kwtjIpaRsQbUtMpvfXlVK1R0Nd3lhRu3Q9TRxtbLLdoXl6cf6Ub/eMVFA5NELsWV2qyDkMDKMf3HXLlGvk+TBiYsnqBbx/V8SxGrE9IQ+8jEq4Znk40Y8pEoJL/tTlLOWlD1nH4RgZSLc+WTuwqKjm8E604sSbCy5eg="

before_install:
  # repo for Qt
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq update

  # compiled OSG
  - wget https://github.com/vicrucann/OpenSceneGraph/releases/download/OpenSceneGraph-3.4.0/osg-340-deb.tar.gz
  - tar -zxvf osg-340-deb.tar.gz

install:
  - sudo apt-get --yes install qt55base qt55imageformats qt55svg
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

  # copy OSG to standard location so that cmake is able to find it
  - sudo cp -rv osg-340-deb/lib64 /usr/local/
  - sudo cp -rv osg-340-deb/include /usr/local/
  - sudo cp -rv osg-340-deb/bin /usr/local/

before_script:
  # Qt variables
  - QTDIR="/opt/qt55"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt55/bin/qt55-env.sh

  # OpenSceneGraph variables
  - export LD_LIBRARY_PATH="/usr/local/lib64:/usr/local/lib:$LD_LIBRARY_PATH"
  - export OPENTHREADS_INC_DIR="/usr/local/include"
  - export OPENTHREADS_LIB_DIR="/usr/local/lib64:/usr/local/lib"
  - export PATH="$OPENTHREADS_LIB_DIR:$PATH"

  # cmake build of the project
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt55/lib/cmake 

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi

  - make
