language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "PZXQAOCDQX22qB8wvwYAetY+6O/KkumZ8zJhhG3Sy8cIYz2m3UkRl2pyqtk6vxAN+6D5whb8A4nBzkqKah+BBlCwNY/88+p/OkZozR3zeVACFVORBfv2ZWfsYWbQolOSF1sJP+MlqsSEtG68BBGFNG9J2c+u5Z9SV+D4B1oUb/14OmFH24FzPIIOq3i0lPPRt1GYcJtwDIy+sD8/q66+ftOpOtXSWNNsNanCPibZtq1iHAQLkiBoNCOrUYDM+SVyQGv5hw5u/2GE1golvR9BZu4UOXM+E4OgiZOx2I3GIpCzXLcCDwi6GoFRCKqG3KfHmMDfQjfgPsVp8qRQUc4LTwnP1PcuDSWPfjePUMFs3JgrvFFM6nioXith2Mkr7O0bXv8njAdxjyuQ+vz2fHcmMjZ7GqtOouL2TeVryVtM2BaNTrKaF1RaLvYqEjPsbEYt87QNEuO7tc3y6OiEuFjAatniTpozv4cFw21641QfEC12hvTvOAyXWXbYD0aZBXOVbj20aDG6uSLPimg9J8pBV8mdcIGINAdDWNxmkCr5Na+0TsfDXNcDeylcETLdk9KZ9dApoAahfVhDXFYt/VuaPP+YO4QPSqHapuByBq29f8pvSQ9ioRZfedmDrr6BTfcrHcXO0ZdNJiO25NXNxJQbga0jqVYvYKMyCnowzUFuErA="

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

  coverity_scan:
    project:
      name: "vicrucann/QtOSG-hello"
      description: "Build submitted via Travis CI of Qt + OpenSceneGraph application"
    notification_email: vicrucann@gmail.com
    build_command:   "make VERBOSE=1"
    branch_pattern: coverity_scan

before_install:
  # repo for Qt
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq update

  # compiled OSG
  - wget https://github.com/vicrucann/OpenSceneGraph/releases/download/OpenSceneGraph-3.4.0/osg-340-deb.tar.gz
  - tar -zxvf osg-340-deb.tar.gz

install:
  - sudo apt-get --yes install qt55base qt55imageformats qt55svg
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

  # copy OSG to standard location so that cmake is able to find it
  - sudo cp -rv osg-340-deb/lib64 /usr/local/
  - sudo cp -rv osg-340-deb/include /usr/local/
  - sudo cp -rv osg-340-deb/bin /usr/local/

before_script:
  # Qt variables
  - QTDIR="/opt/qt55"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt55/bin/qt55-env.sh

  # OpenSceneGraph variables
  - export LD_LIBRARY_PATH="/usr/local/lib64:/usr/local/lib:$LD_LIBRARY_PATH"
  - export OPENTHREADS_INC_DIR="/usr/local/include"
  - export OPENTHREADS_LIB_DIR="/usr/local/lib64:/usr/local/lib"
  - export PATH="$OPENTHREADS_LIB_DIR:$PATH"

  # cmake build of the project
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt55/lib/cmake 

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi

  - make
